title: Anshuman Singh's Blog
description: >
  Hi, I am **Anshuman Singh**, a **Full Stack Developer**
copyright: Anshuman Singh
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username:
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  "singh-anshuman"
feed_icon: rss
email: "connect@singh-anshuman.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
github:
    url:https://github.com/singh-anshuman
